name: Java CI

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: ppgame
        path: target/*.jar
